name: science_hall
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"



dependencies:
  flutter:
    sdk: flutter


  arc:
    git: https://github.com/akthfdyd/arc.git

  get_it: ^7.2.0

  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  http: ^0.13.5
  cached_network_image: ^3.2.1
  flutter_riverpod: ^2.0.0-dev.9

  # For UIs
  gap: ^2.0.0
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2

  auto_route: ^4.0.1
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0


  flutter_staggered_animations:
    git:
      url: https://github.com/faisal-kabir/flutter_staggered_animations.git
      ref: develop
  flutter_beacon: ^0.5.1
  shared_preferences: ^2.0.15
  device_info: ^2.0.3
  permission_handler: ^10.0.0
  pull_to_refresh_flutter3: ^2.0.1
  kakaomap_webview: ^0.6.2
  fluttertoast: ^8.0.9





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.0.0



flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - mockdata/



